version: 2.1
jobs:
  build:
    machine:
      enabled: true
      # Use Ubuntu 14.04 with bleeding edge Docker daemon 17.06.0-ce.
      image: ubuntu-2004:202201-02 
    steps:
        - checkout
        - run:
            name: The First Step
            command: |
              echo 'Hello World!'
              echo 'This is the delivery pipeline'
        - checkout
        - run:
            name: run permissions
            command: cd configuration_script && sudo chmod 777 * 
        - checkout
        - run:
            name: run script
            command: cd configuration_script && cat input.txt | bash configuration.sh 
      #  - checkout
       # - run:
        #    name: run script
         #   command: cd configuration_script && cat input.txt | bash configuration1.sh 
