version: 2.1
jobs:
  build:
    docker:
      - image: "amd64/debian:buster-slim"   
    steps:
        - checkout
        - run:
            name: The First Step
            command: |
              echo 'Hello World!'
              echo 'This is the delivery pipeline'
