version: 2.1
jobs:
  build:
    machine:
      enabled: true
      # Use Ubuntu 14.04 with bleeding edge Docker daemon 17.06.0-ce.
      image: debian 
    steps:
        - checkout
        - run:
            name: The First Step
            command: |
              echo 'Hello World!'
              echo 'This is the delivery pipeline'
